# What is the difference list and numpy?
While both Python **lists** and NumPy **arrays** are used to store collections of data, they are completely different under the hood.

The core difference is that a standard Python list is a general-purpose, flexible container designed for everyday programming, while a NumPy array is a specialized, high-performance data structure built specifically for **mathematical computations and data science**.

Here is a direct breakdown of why and how they differ:

---

## Direct Comparison

| Feature | Python List | NumPy Array (`ndarray`) |
| --- | --- | --- |
| **Data Types** | Can hold **multiple data types** at once (e.g., `[1, "hello", 3.4]`). | Can only hold **one data type** (homogeneous). If you mix types, it forces them into one type. |
| **Memory Efficiency** | **Inefficient**. It stores pointers to objects scattered across your memory. | **Highly efficient**. Data is stored in a single, continuous block of memory. |
| **Mathematical Operations** | Does **not** support direct math. Operations like `+` will duplicate or join the lists. | Supports **vectorized operations**. Operations are applied instantly to every element. |
| **Performance** | Slower for large datasets because loops are executed in Python. | Blazing fast. The underlying loops are written in highly optimized C. |

---

## 1. How They Handle Math (Vectorization)

If you try to multiply a standard Python list, it doesn't multiply the numbers inside—it duplicates the list structure itself. NumPy, however, treats arrays like mathematical matrices.

```python
import numpy as np

# --- The Python List Way ---
my_list = [1, 2, 3]
print(my_list * 2)  
# Output: [1, 2, 3, 1, 2, 3] (It duplicated the list!)

# To actually multiply it, you are forced to write a loop:
list_result = [x * 2 for x in my_list] # [2, 4, 6]


# --- The NumPy Way ---
my_array = np.array([1, 2, 3])
print(my_array * 2)  
# Output: [2 4 6] (Vectorized math!)

```

---

## 2. Memory Allocation Under the Hood

This is the main reason NumPy leaves standard lists in the dust when it comes to speed.

* **Python Lists:** A list is actually an array of pointers. Each pointer points to a completely separate Python object elsewhere in memory. Because the numbers aren't sitting next to each other, your computer's CPU has to jump around in memory to read them (causing "cache misses").
* **NumPy Arrays:** NumPy allocates a single, continuous block of memory where raw data sits side-by-side. Your CPU can read the entire block in one lightning-fast sweep.

---

## Summary Guideline: When to use which?

* Use a **Python List** when you have a small collection of items, when your data contains mixed types (like strings and integers together), or when you need to dynamically add and remove items frequently.
* Use a **NumPy Array** anytime you are doing numerical analysis, matrix math, statistics, or processing large tabular datasets.

In [0]:
import numpy as np
nums = np.array([10,20,30,40])
print(nums*2)

martrix = np.array([
    [1,2,3],
    [3,4,4],
    [5,6,7]
])
print(martrix)

print("------------------")
# let us defien a 3D array as well
array3D = np.array([
    [[1,2,3],
     [4,5,6]
    ],
    [[7,8,9],
     [10,11,12]
    ]
])
print(array3D)

print("Demensions of the array is :",array3D.ndim)
print("Shape of the array is :",array3D.shape)
print("Size of the array is :",array3D.size)
print("Data type of the array is :",array3D.dtype)
print("Data type of the array is :",array3D.itemsize)
print(array3D[0][1][2])



[20 40 60 80]
[[1 2 3]
 [3 4 4]
 [5 6 7]]
------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Demensions of the array is : 3
Shape of the array is : (2, 2, 3)
Size of the array is : 12
Data type of the array is : int64
Data type of the array is : 8
6


In [0]:
marks = np.array([10,20,30,50,98])
print(marks)
print("Number of students:", marks.size)
print("Average marks:", marks.mean())
print("Minimum marks:", marks.min())
print("Maximum marks:", marks.max())
print("Standard deviation:", marks.std())
print("Variance:", marks.var())
print("Median:", np.median(marks))
print("Percentile:", np.percentile(marks, 50))
print("Unique values:", np.unique(marks))
print("Unique values and their counts:", np.unique(marks, return_counts=True))
print("Unique values and their indices:", np.unique(marks, return_index=True))


[10 20 30 50 98]
Number of students: 5
Average marks: 41.6
Minimum marks: 10
Maximum marks: 98
Standard deviation: 31.148675734290855
Variance: 970.24
Median: 30.0
Percentile: 30.0
Unique values: [10 20 30 50 98]
Unique values and their counts: (array([10, 20, 30, 50, 98]), array([1, 1, 1, 1, 1]))
Unique values and their indices: (array([10, 20, 30, 50, 98]), array([0, 1, 2, 3, 4]))
